# Generated by Django 4.2+ on 2026-06-02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('template_message', models.TextField()),
                ('object_id', models.PositiveBigIntegerField(null=True)),
                ('tool', models.CharField(max_length=100)),
                ('action', models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('access', 'Access')], max_length=50)),
                ('changes', models.JSONField(blank=True, null=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='actor_eventlogs', to=settings.AUTH_USER_MODEL)),
                ('object_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Event Log',
                'verbose_name_plural': 'Event Logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='RelatedValueEventLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_format', models.TextField()),
                ('object_id', models.PositiveBigIntegerField(null=True)),
                ('default_value', models.TextField(default='')),
                ('log', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='related_values', to='django_simple_eventlog.eventlog')),
                ('object_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Related Value Event Log',
                'verbose_name_plural': 'Related Value Event Logs',
            },
        ),
    ]
